edition = "2024"
hard_tabs = true
newline_style = "unix"
fn_params_layout = "Compressed"
#binop_separator = "Front"
#condense_wildcard_suffixes = true
#imports_layout = "HorizontalVertical"
#imports_granularity = "Module"
#normalize_comments = true
#normalize_doc_attributes = true
#group_imports = "StdExternalCrate"
max_width = 160
single_line_if_else_max_width = 120
single_line_let_else_max_width = 120
fn_call_width = 120
attr_fn_like_width = 120
struct_lit_width = 120
struct_variant_width = 120
array_width = 120
chain_width = 120
